const array = [
    {id:1,href:"https://es6.ruanyifeng.com/",discription:"阮一峰 es6入门教程"},
    {id:2,href:"http://www.ruanyifeng.com/home.html",discription:"阮一峰 个人博客"},
    {id:3,href:"https://www.bootcdn.cn/",discription:"cdn汇总"},
    {id:4,href:"http://www.animate.net.cn/",discription:"Animate中文网 css3动画库"},
    {id:5,href:"https://www.html5iq.com/5feb26ddf72c21052324d0fd.html",discription:"前端知识库 前端面试题大全"},
    {id:6,href:"https://juejin.cn/post/6892003555818143752#heading-51",discription:"手把手带你入门前端工程化——超详细教程 前端工程化"},
    {id:7,href:"https://www.zhangxinxu.com/",discription:"张鑫旭的个人主页"},
    {id:8,href:"https://codetop.cc/home",discription:"codeTop 企业题库"},
    {id:9,href:"https://www.jianshu.com/p/6a07e974a7e8",discription:"html2canvas 网页截屏"},
    {id:10,href:"http://www.fontawesome.com.cn/faicons/",discription:" Font Awesome 中文网"},
    {id:11,href:"https://segmentfault.com/a/1190000018914486",discription:"video.js的使用及问题"},
    {id:12,href:"https://www.jianshu.com/p/073f79c5e438",discription:"js获取页页面URL"},
    {id:13,href:"https://www.cnblogs.com/wayou/p/jquery_plugin_tutorial.html",discription:"jQury插件开发"},
    {id:14,href:"https://developer.mozilla.org/zh-CN/",discription:"MDN文档"},
    {id:15,href:"https://visualgo.net/en",discription:"算法动态图演示网站"},
    {id:16,href:"https://juejin.cn/post/6844903767226351623",discription:"九种浏览器跨域解决办法"},
    {id:17,href:"https://www.kancloud.cn/dennis/tgjavascript",discription:"JavaScript半知半解"},
    {id:18,href:"http://graphics.stanford.edu/~seander/bithacks.html#OperationCounting",discription:"斯坦福大学知识图谱课程"},
    {id:19,href:"https://blog.csdn.net/HUSTHY/article/details/105882989",discription:"bert模型简介、transformers中bert模型源码阅读、分类任务实战和难点总结"},
    {id:20,href:"https://github.com/XiangLinPro/IT_book",discription:"IT books"},
    {id:21,href:"https://zhuanlan.zhihu.com/p/76003775",discription:"文本分类算法综述"},
    {id:22,href:"https://blog.csdn.net/qq_38807395/article/details/103494078",discription:"你不知道的 JSON.stringify() 的威力"},
    {id:23,href:"https://www.cnblogs.com/xiaohuochai/p/5314289.html",discription:"深入理解CSS中的margin负值"},
    {id:24,href:"https://mp.weixin.qq.com/s/4eqA7IokLBGPmNcQqCnFUg",discription:"阿里巴巴专有钉钉前端面试指南"},
    {id:25,href:"https://juejin.cn/post/6940942549305524238",discription:"掘金 CUGGZ 高频前端面试题汇总"},
    {id:26,href:"https://www.yuque.com/cuggz/interview",discription:"语雀 CUG-GZ 前端面试题汇总"},
    {id:27,href:"https://segmentfault.com/a/1190000039343974",discription:"前端面试宝典：react核心知识篇"},
    {id:28,href:"https://www.cnblogs.com/shoshana-kong/p/10994889.html",discription:"初次使用git配置以及git如何使用ssh密钥"},
    {id:29,href:"https://www.cnblogs.com/yangzhou33/p/8480140.html",discription:"create-react-app脚手架中配置webpack的方法"},
    {id:30,href:"https://www.jianshu.com/p/bbdf2a50903a",discription:"react脚手架 + antd的craco.config.js配置"},
    {id:31,href:"https://www.cnblogs.com/saolv/p/12793637.html",discription:"在linux上通过ssh使用github"},
    {id:32,href:"https://blog.csdn.net/qq_42815754/article/details/82980326",discription:"Linux下nginx的安装以及环境配置"},
    {id:33,href:"https://blog.csdn.net/weixin_33913332/article/details/91706716",discription:"关于proxy_pass的参数路径问题"},
    {id:34,href:"https://www.liaoxuefeng.com/",discription:"廖雪峰的官方网站"},
    {id:35,href:"https://github.com/haoel/leetcode",discription:"力扣题解"},
    {id:36,href:"https://wizardforcel.gitbooks.io/the-art-of-programming-by-july/content/06.07.html",discription:"编程之法：面试和算法心得"},
    {id:37,href:"https://segmentfault.com/a/1190000021966814",discription:"Web 中高级前端面试题集合（200+）"},
    {id:38,href:"https://github.com/paddingme/Front-end-Web-Development-Interview-Question",discription:"前端面试笔试题"},
    {id:39,href:"https://www.cnblogs.com/my466879168/p/13681479.html",discription:"react项目中使用less"},
]

export default array;